name: CI
on:
  push:
    branches: [ main ]
  pull_request:
    types:
      - opened
    branches: [ main ]
jobs:
  test-script:
    runs-on: ubuntu-latest
    container: dtzar/helm-kubectl:3.13.0
    steps:
      - uses: actions/checkout@v3

      - run: ./test.sh
